### ISSUE TITLE
Extension not grabbing the default value

### ISSUE THREAD

**Issue by andreboscatto** [ciandt-dev/behat-placeholders-extension#1]
When not defining the properly value on an environment, the default value is not used during the execution. Ex:

lang_url: 
```
        $default:
            $pt: /?hl=pt
            $br: /?hl=pt-br
            $us: /?hl=en
            $de: /?hl=de
        $development:
            $br: /hl=pt-br
            $us: /hl=en
```
In the example above, when used -e development the values from $de and $pt are not being set with $default values.
